import { Suspense } from 'react'
import { Metadata } from 'next'
import InfiniteJobList from '@/components/InfiniteJobList'
import JobFilters from '@/components/JobFilters'
import { Phone, Home, DollarSign, ShieldCheck, Award, Users, TrendingUp } from 'lucide-react'
import { getJobs } from '@/lib/getJobs'


export const revalidate = 3600

export const metadata: Metadata = {
  title: 'Solar Sales Jobs | D2D, In-Home & Technical Sales Openings',
  description: 'Solar sales positions across the United States \u2014 door-to-door, in-home, inside sales, and technical sales roles. Commission structures, what employers screen for, and realistic pay ranges.',
  keywords: 'solar sales jobs, solar sales rep jobs, door to door solar sales, in home solar sales, solar sales consultant, solar technical sales, solar sales engineer jobs',
  openGraph: {
    title: 'Solar Sales Jobs | Now Hiring Nationwide',
    description: 'Browse open solar sales positions \u2014 D2D, in-home, inside sales, and technical sales roles with commission structures explained.',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Solar Sales Jobs',
    description: 'Find solar sales openings across the US. D2D, in-home, inside sales, and technical sales employers hiring now.',
  },
  alternates: { canonical: 'https://www.solarroles.com/solar-sales-jobs' },
}

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebPage',
  name: 'Solar Sales Jobs',
  description: 'Solar sales job listings across the United States, covering door-to-door, in-home, inside sales, and technical sales roles.',
  url: 'https://www.solarroles.com/solar-sales-jobs',
  mainEntity: {
    '@type': 'ItemList',
    name: 'Available Solar Sales Jobs',
    description: 'Current solar sales job listings',
  },
}

const salesRoles = [
  {
    title: 'Door-to-Door (D2D) Sales Rep',
    description: "Canvasses neighborhoods to generate and close leads directly, often working set territories with a canvassing app to track doors knocked. Almost entirely commission-driven, with the highest earning ceiling and the highest turnover of any role on this list.",
    icon: Phone,
  },
  {
    title: 'In-Home Sales Consultant',
    description: "Runs the sales appointment itself \u2014 presenting system design, financing options, and closing the contract in the customer's home. Leads are usually handed off from a setter or marketing team rather than self-generated.",
    icon: Home,
  },
  {
    title: 'Inside Sales / Call Center Rep',
    description: "Works inbound and outbound leads by phone to book appointments or close smaller deals remotely. Lower commission ceiling than field sales, but steadier hours and a lower bar to entry.",
    icon: Phone,
  },
  {
    title: 'Solar Sales Engineer / Technical Sales',
    description: "Pairs sales with system design competence \u2014 sizing systems, explaining production estimates, and handling technical objections that a generalist rep would escalate. NABCEP PV Technical Sales certification comes up specifically for this track.",
    icon: Award,
  },
  {
    title: 'Channel / Partner Sales Manager',
    description: "Manages relationships with roofing companies, electricians, or other contractors who refer solar leads, rather than selling to homeowners directly. A common step up after a few years closing deals individually.",
    icon: Users,
  },
]

const faqs = [
  {
    question: 'Is solar sales all commission, or is there a base salary?',
    answer: "Most postings combine a modest base with commission that makes up the majority of total pay, though the ratio varies a lot by company and channel. Pure-commission D2D roles exist, but salaried-with-commission structures are more common for in-home and inside sales.",
  },
  {
    question: 'How much can top performers actually earn?',
    answer: "Top D2D and in-home reps commonly clear $100,000 to $150,000+ in strong markets, since commission is usually paid per watt or per system rather than capped. Mid-performers land well below that \u2014 the spread between top and median earners is wider in solar sales than in most sales jobs.",
  },
  {
    question: 'Do you need a license to sell solar?',
    answer: "It depends on the state. Some require a home improvement or contractor sales license for door-to-door or in-home solar sales specifically, and a few require a separate license for anyone discussing financing terms. Check your state's requirements directly, since this varies more than most other solar roles.",
  },
  {
    question: "What's the difference between D2D and in-home sales?",
    answer: "A D2D rep generates their own leads by knocking doors and closes on the spot or books a follow-up. An in-home consultant typically receives leads already generated by someone else and focuses purely on the appointment and close. D2D has a higher ceiling but more volatility; in-home is steadier.",
  },
  {
    question: 'Do you need technical solar knowledge to get hired?',
    answer: "Not for most entry-level sales roles \u2014 companies train reps on system basics, financing products, and objection handling. Technical sales and sales engineer roles are the exception, where system design knowledge is part of the job from day one.",
  },
  {
    question: 'Is solar sales a good way to break into the industry with no experience?',
    answer: "It's one of the more accessible entry points, since most companies hire on sales aptitude rather than solar background and train the technical content on the job. It's a different track than installation, though \u2014 moving from sales into a technical or install role isn't automatic.",
  },
]

export default async function SolarSalesJobsPage({ searchParams }: any) {
  const params = await searchParams

  const initialData = await getJobs({
    // Scopes this landing page to sales roles via a keyword AND-filter,
    // independent of the user's own `what` search box below — same
    // pattern used on /lead-solar-installer-jobs and
    // /solar-jobs-no-experience.
    descriptionContainsAny: ['solar sales', 'sales representative', 'sales consultant', 'sales engineer', 'account executive', 'door to door', 'd2d'],
    requiredDomainTerms: ['sales', 'Sales'],
    ...(params.what ? { what: params.what } : {}),
    where: params.where || '',
    resultsPerPage: 30,
    salaryMin: params.salary_min ? Number(params.salary_min) : undefined,
    postedWithin: params.posted_within ? Number(params.posted_within) : undefined,
    jobTypes: params.job_type ? params.job_type.split(',') : undefined,
    arrangements: params.arrangement ? params.arrangement.split(',') : undefined,
    experience: params.experience || undefined,
    education: params.education || undefined,
    companySizes: params.company_size ? params.company_size.split(',') : undefined,
    benefits: params.benefits ? params.benefits.split(',') : undefined,
    easyApply: params.easy_apply === 'true',
  })

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <div className="max-w-7xl mx-auto px-6 py-12">
        <header className="mb-10">
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3">Solar Sales Jobs</h1>
        </header>

        <div className="flex flex-col lg:flex-row gap-10">

          <aside className="lg:w-80"><JobFilters /></aside>
          <div className="flex-1">
            <Suspense fallback={<div className="animate-pulse bg-gray-100 rounded-lg h-96" />}>
              <InfiniteJobList
                what={params.what || ''}
                searchLabel="solar sales "
                where={params.where || ''}
                salary_min={params.salary_min}
                initialData={initialData}
              />
            </Suspense>
          </div>
        </div>

        <section className="mt-20">
          <div className="flex items-center gap-3 mb-6"><Phone className="w-7 h-7 text-orange-500" /><h2 className="text-2xl font-bold text-gray-900">Types of Solar Sales Roles</h2></div>
          <p className="text-gray-600 mb-6 max-w-4xl">
            "Solar sales" covers roles with genuinely different day-to-day work and pay structures. Where a lead comes from \u2014 self-generated at the door, handed off from a setter, or inbound \u2014 changes almost everything about the job.
          </p>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {salesRoles.map((role, index) => (
              <div key={index} className="bg-gradient-to-br from-gray-50 to-white border border-gray-200 rounded-xl p-6 hover:shadow-lg transition-all">
                <role.icon className="w-10 h-10 text-orange-500 mb-4" />
                <h3 className="font-semibold text-gray-900 text-lg mb-2">{role.title}</h3>
                <p className="text-gray-600 text-sm">{role.description}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-20">
          <div className="flex items-center gap-3 mb-6"><ShieldCheck className="w-7 h-7 text-blue-600" /><h2 className="text-2xl font-bold text-gray-900">What These Roles Actually Require</h2></div>
          <p className="text-gray-600 mb-4 max-w-4xl">
            Most solar sales postings don't require a technical background \u2014 they screen for sales aptitude, resilience for door-to-door or cold outreach, and comfort presenting financing options (loan, lease, or PPA) rather than solar knowledge itself. Companies typically train the technical content during onboarding.
          </p>
          <p className="text-gray-600 max-w-4xl">
            The exception is technical sales and sales engineer roles, where system design competence is expected from the start and NABCEP's PV Technical Sales credential shows up as a differentiator. State licensing requirements for home improvement or contractor sales also apply in some states specifically for door-to-door and in-home solar \u2014 worth checking before assuming a posting's requirements are generic.
          </p>
        </section>

        <section className="mt-20">
          <div className="flex items-center gap-3 mb-6"><DollarSign className="w-7 h-7 text-green-600" /><h2 className="text-2xl font-bold text-gray-900">Solar Sales Pay & Commission</h2></div>
          <p className="text-gray-600 mb-6 max-w-4xl">
            Solar sales isn't tracked as its own category by the Bureau of Labor Statistics, so the ranges below reflect typical figures reported in industry postings rather than a government statistic \u2014 treat them as directional, and expect real variance by company, region, and lead source.
          </p>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="bg-white rounded-xl p-5 text-center border border-gray-200">
              <p className="text-3xl font-bold text-green-600 mb-2">$40-60K</p>
              <p className="text-sm font-semibold text-gray-700 mb-1">Inside Sales / New Reps</p>
              <p className="text-xs text-gray-500">Base + commission, first year typical</p>
            </div>
            <div className="bg-white rounded-xl p-5 text-center border border-gray-200">
              <p className="text-3xl font-bold text-blue-600 mb-2">$70-100K</p>
              <p className="text-sm font-semibold text-gray-700 mb-1">Established D2D / In-Home Reps</p>
              <p className="text-xs text-gray-500">Consistent closer, steady lead flow</p>
            </div>
            <div className="bg-white rounded-xl p-5 text-center border border-gray-200">
              <p className="text-3xl font-bold text-purple-600 mb-2">$100-150K+</p>
              <p className="text-sm font-semibold text-gray-700 mb-1">Top Performers</p>
              <p className="text-xs text-gray-500">Strong markets, high close rate</p>
            </div>
          </div>
        </section>

        <section className="mt-20">
          <div className="flex items-center gap-3 mb-6"><TrendingUp className="w-7 h-7 text-orange-500" /><h2 className="text-2xl font-bold text-gray-900">Job Outlook</h2></div>
          <p className="text-gray-600 max-w-4xl">
            The Bureau of Labor Statistics projects 42% employment growth for solar photovoltaic installers between 2024 and 2034 \u2014 sales isn't the same occupation, but every new install crew traces back to a closed sale, so hiring in solar sales tends to track installation growth closely.
          </p>
        </section>

        <section className="mt-20">
          <div className="flex items-center gap-3 mb-6"><Award className="w-7 h-7 text-blue-600" /><h2 className="text-2xl font-bold text-gray-900">Solar Sales Job FAQ</h2></div>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <details key={index} className="group bg-white border border-gray-200 rounded-xl overflow-hidden">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gray-50 transition-colors">
                  <h3 className="font-semibold text-gray-900 pr-4">{faq.question}</h3>
                  <span className="text-gray-400 group-open:rotate-180 transition-transform">
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
                  </span>
                </summary>
                <div className="px-6 pb-6 text-gray-600">{faq.answer}</div>
              </details>
            ))}
          </div>
        </section>

        <section className="mt-20 border-t border-gray-200 pt-10">
          <p className="text-sm text-gray-500 max-w-4xl">
            <strong>Disclaimer:</strong> Pay ranges reflect typical figures reported across industry job postings, not a Bureau of Labor Statistics occupation \u2014 solar sales isn't tracked as a distinct category. Actual compensation varies significantly by employer, lead source, region, and individual performance. Verify licensing requirements directly with your state.
          </p>
        </section>
      </div>
    </>
  )
}