import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://www.oh-my-job.com',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: 'https://www.oh-my-job.com/jobs',
      lastModified: new Date(),
      changeFrequency: 'hourly', // les offres changent souvent
      priority: 0.9,
    },
    {
      url: 'https://www.oh-my-job.com/jobs-for-14-year-olds',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.oh-my-job.com/jobs-for-15-year-olds',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.oh-my-job.com/jobs-for-16-year-olds',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.oh-my-job.com/fifo-jobs',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.oh-my-job.com/allied-universal-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/cna-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/dental-assistant-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/dignity-health-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/oil-rig-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/pharmacy-technician-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/project-manager-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/amgen-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/armed-security-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/city-of-reno-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/healthcare-administration-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/press-association-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/substitute-teacher-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/ucsd-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/burger-king-corporation-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/ekg-technician-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/engineering-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/executive-assistant-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/heavy-equipment-operator-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/hvac-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/jobs-at-property-management',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/live-nation-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/nanny-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/pct-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },


    {
      url: 'https://www.oh-my-job.com/barista-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/bartending-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/cintas-company-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/customer-service-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/daycare-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/electrician-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/medical-assistant-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/front-desk-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/part-time-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/planet-fitness-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    {
      url: 'https://www.oh-my-job.com/welding-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/assisted-reproductive-technology-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/chick-fil-a-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/exelon-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/housekeeping-jobs-near-you',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/honda-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/school-nurse-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/paraprofessional-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/sonic-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/national-grid-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/cardinal-health-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/patient-transporter-jobs',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
     {
      url: 'https://www.oh-my-job.com/doordash-careers',
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.3,
    },
    
  ]
}