import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const DEFAULT_INPUT = path.join(process.cwd(), 'data', 'texas-solar-electrical-contractors', 'texas-solar-domain-candidates.csv')
const DEFAULT_OUTPUT = path.join(process.cwd(), 'data', 'texas-solar-electrical-contractors', 'texas-solar-career-audit.csv')
const MIN_JOBS = 3
const ATS = ['adp.com', 'applicantpro.com', 'applytojob.com', 'bamboohr.com', 'breezy.hr', 'ceridian.com', 'dayforcehcm.com', 'greenhouse.io', 'icims.com', 'jazz.co', 'jazzhr.com', 'jobvite.com', 'lever.co', 'myworkdayjobs.com', 'paycomonline.net', 'paylocity.com', 'rippling.com', 'smartrecruiters.com', 'talentreef.com', 'teamtailor.com', 'ukg.net', 'ultipro.com', 'workable.com']
const PROBES = ['/careers', '/jobs', '/career', '/employment', '/about/careers', '/about/career-opportunities', '/join-us']
type Row = Record<string, string>

function parseCsv(source: string): Row[] { const records: string[][] = []; let record: string[] = [], field = '', quoted = false; for (let i = 0; i < source.length; i += 1) { const char = source[i]; if (quoted) { if (char === '"' && source[i + 1] === '"') { field += char; i += 1 } else if (char === '"') quoted = false; else field += char } else if (char === '"') quoted = true; else if (char === ',') { record.push(field); field = '' } else if (char === '\n') { record.push(field.replace(/\r$/, '')); records.push(record); record = []; field = '' } else field += char }; if (field || record.length) { record.push(field); records.push(record) }; const [headers = [], ...rows] = records; return rows.filter((row) => row.some(Boolean)).map((row) => Object.fromEntries(headers.map((header, i) => [header, row[i] ?? '']))) }
function esc(value: unknown) { const text = String(value ?? ''); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }
function host(url: string) { try { return new URL(url).hostname.replace(/^www\./, '').toLowerCase() } catch { return '' } }
function internal(url: string, domain: string) { const value = host(url); return value === domain || value.endsWith(`.${domain}`) }
function hasAts(url: string, html = '') { const value = host(url); return ATS.some((entry) => value === entry || value.endsWith(`.${entry}`) || html.includes(entry)) }
function jobPosting(html: string) { return /["']@type["']\s*:\s*(?:\[[^\]]*)?["']JobPosting["']/i.test(html) }
function links(html: string, base: string) { const output: string[] = []; for (const match of html.matchAll(/<a\b[^>]*?href\s*=\s*["']([^"'#]+)["']/gi)) try { output.push(new URL(match[1], base).href) } catch {} return [...new Set(output)] }
function careerUrl(url: string) { try { return /(^|\/)(?:careers?|jobs?|employment|openings?|positions?)(?:[\/_-]|$)|(^|\/)(?:join-us|work-with-us)(?:\/|$)/i.test(new URL(url).pathname) } catch { return false } }
function jobDetailUrl(url: string, domain: string) { try { if (!internal(url, domain) || !careerUrl(url)) return false; const pathname = new URL(url).pathname.toLowerCase(); const tail = pathname.split('/').filter(Boolean).at(-1) ?? ''; return !/^(job|jobs|career|careers|employment|position|positions|opening|openings|opportunities|vacancies|join-us)$/.test(tail) && !/(apply|application|category|tag|blog|news)/.test(pathname) } catch { return false } }
function plainText(html: string) { return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/gi, ' ').replace(/&amp;/gi, '&').replace(/\s+/g, ' ').trim() }
function words(text: string) { return text.match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu)?.length ?? 0 }
function completeJob(html: string, row: Row) { const text = plainText(html), wordCount = words(text); const city = row.cityStateZip.match(/^(.+?)\s+TX\s+\d{5}/)?.[1] ?? ''; const location = /\b(location|remote|hybrid|on[- ]site|based in|work location)\b/i.test(text) || Boolean(city && text.toLowerCase().includes(city.toLowerCase())) || /\b(?:TX|Texas)\b/.test(text); const employmentType = /\b(full[- ]?time|part[- ]?time|contract(?:or)?|temporary|seasonal|intern(?:ship)?|1099|per[- ]?diem|prn)\b/i.test(text); const structure = /\b(responsibilit(?:y|ies)|duties|requirements|qualifications|job description|what you(?:'|’)ll do)\b/i.test(text); return { ok: wordCount >= 300 && location && employmentType && structure, wordCount } }

async function get(url: string) { const response = await fetch(url, { redirect: 'follow', headers: { 'User-Agent': 'SolarRoles research bot/1.0 (+https://solarroles.com)' }, signal: AbortSignal.timeout(20_000) }); return { url: response.url, ok: response.ok, status: response.status, html: await response.text() } }
async function robotsAllows(domain: string) { try { const response = await get(`https://${domain}/robots.txt`); if (!response.ok) return true; const wildcard = response.html.split(/\n\s*\n/).filter((group) => /^\s*user-agent:\s*\*/im.test(group)).join('\n'); return !/^\s*disallow:\s*\/$/im.test(wildcard) } catch { return true } }
async function write(outputPath: string, rows: Row[]) { const headers = ['licenseNumber', 'businessName', 'cityStateZip', 'candidateDomain', 'careerUrl', 'jobUrls', 'jobUrlCount', 'validJobPages', 'maxDescriptionWords', 'atsDetected', 'jobPostingDetected', 'auditStatus', 'auditReason']; await writeFile(outputPath, `${headers.join(',')}\n${rows.map((row) => headers.map((header) => esc(row[header])).join(',')).join('\n')}\n`, 'utf8') }

async function audit(row: Row): Promise<Row> {
  const domain = row.candidateDomain; let career = '', details: string[] = [], valid = 0, maxWords = 0, ats = false, schema = false
  try {
    if (!await robotsAllows(domain)) return { ...row, careerUrl: '', jobUrls: '', jobUrlCount: '0', validJobPages: '0', maxDescriptionWords: '0', atsDetected: 'false', jobPostingDetected: 'false', auditStatus: 'skipped_robots_disallow', auditReason: 'robots.txt disallows all crawling for User-agent *.' }
    const home = await get(`https://${domain}`); if (!home.ok) throw new Error(`Homepage HTTP ${home.status}`)
    let discovered = links(home.html, home.url).filter((url) => internal(url, domain)); career = discovered.find(careerUrl) ?? ''
    for (const suffix of career ? [] : PROBES) { const probe = await get(`https://${domain}${suffix}`); if (probe.ok && internal(probe.url, domain)) { career = probe.url; discovered = [...new Set([...discovered, ...links(probe.html, probe.url)])]; break } }
    if (!career) return { ...row, careerUrl: '', jobUrls: '', jobUrlCount: '0', validJobPages: '0', maxDescriptionWords: '0', atsDetected: 'false', jobPostingDetected: 'false', auditStatus: 'rejected_no_careers_page', auditReason: 'No provider-hosted careers/jobs landing page found from homepage or standard paths.' }
    const landing = await get(career); ats = hasAts(landing.url, landing.html); schema = jobPosting(landing.html); details = [...new Set([...discovered, ...links(landing.html, landing.url)])].filter((url) => jobDetailUrl(url, domain))
    if (ats) return { ...row, careerUrl: career, jobUrls: details.join('|'), jobUrlCount: String(details.length), validJobPages: '0', maxDescriptionWords: '0', atsDetected: 'true', jobPostingDetected: String(schema), auditStatus: 'rejected_ats_detected', auditReason: 'Known ATS domain or embed detected.' }
    if (schema) return { ...row, careerUrl: career, jobUrls: details.join('|'), jobUrlCount: String(details.length), validJobPages: '0', maxDescriptionWords: '0', atsDetected: 'false', jobPostingDetected: 'true', auditStatus: 'rejected_jobposting_detected', auditReason: 'JobPosting schema detected on careers landing page.' }
    if (details.length < MIN_JOBS) return { ...row, careerUrl: career, jobUrls: details.join('|'), jobUrlCount: String(details.length), validJobPages: '0', maxDescriptionWords: '0', atsDetected: 'false', jobPostingDetected: 'false', auditStatus: 'rejected_insufficient_job_urls', auditReason: `Only ${details.length}/${MIN_JOBS} internal detailed job URLs found.` }
    for (const url of details.slice(0, 10)) { const page = await get(url); ats ||= hasAts(page.url, page.html); schema ||= jobPosting(page.html); const check = completeJob(page.html, row); maxWords = Math.max(maxWords, check.wordCount); if (check.ok) valid += 1; if (ats || schema || valid >= MIN_JOBS) break }
    const auditStatus = ats ? 'rejected_ats_detected' : schema ? 'rejected_jobposting_detected' : valid >= MIN_JOBS ? 'validated_custom_scrape_candidate' : 'rejected_incomplete_job_pages'
    const auditReason = ats ? 'Known ATS domain or embed detected on a job page.' : schema ? 'JobPosting schema detected on a job page.' : valid >= MIN_JOBS ? 'At least three detailed static job pages meet completeness rules.' : `Only ${valid}/${MIN_JOBS} pages had location, employment type, structure and 300+ words.`
    return { ...row, careerUrl: career, jobUrls: details.slice(0, 20).join('|'), jobUrlCount: String(details.length), validJobPages: String(valid), maxDescriptionWords: String(maxWords), atsDetected: String(ats), jobPostingDetected: String(schema), auditStatus, auditReason }
  } catch (error) { return { ...row, careerUrl: career, jobUrls: details.join('|'), jobUrlCount: String(details.length), validJobPages: String(valid), maxDescriptionWords: String(maxWords), atsDetected: String(ats), jobPostingDetected: String(schema), auditStatus: 'audit_error', auditReason: error instanceof Error ? error.message : String(error) } }
}

async function main() { const args = process.argv.slice(2), option = (name: string) => { const index = args.indexOf(name); return index >= 0 ? args[index + 1] : undefined }; const limit = Number(option('--limit')) || Number.MAX_SAFE_INTEGER, input = option('--input') ?? DEFAULT_INPUT, outputPath = option('--out') ?? DEFAULT_OUTPUT; const source = parseCsv(await readFile(input, 'utf8')).filter((row) => row.status === 'candidate_found').slice(0, limit); let output: Row[] = []; try { output = parseCsv(await readFile(outputPath, 'utf8')) } catch {}; const done = new Set(output.map((row) => row.licenseNumber)); const pending = source.filter((row) => !done.has(row.licenseNumber)); await mkdir(path.dirname(outputPath), { recursive: true }); console.log(`Domains: ${source.length}; already audited: ${output.length}; remaining: ${pending.length}`); for (const [index, row] of pending.entries()) { const result = await audit(row); output.push(result); await write(outputPath, output); console.log(`[${output.length}/${source.length}] ${row.businessName} — ${result.auditStatus}`); if (index < pending.length - 1) await new Promise((resolve) => setTimeout(resolve, 800)) }; console.log(`Valid: ${output.filter((row) => row.auditStatus === 'validated_custom_scrape_candidate').length}/${output.length}`) }
main()
