import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

type Row = Record<string, string>
type Result = { link?: string }
const INPUT = path.join(process.cwd(), 'data', 'california-solar-contractors', 'solar-contractor-domain-discovery-serper.csv')
const OUTPUT = path.join(process.cwd(), 'data', 'california-solar-contractors', 'solar-career-audit-serper-v5.csv')
const MIN_JOBS = 3
const ATS = ['greenhouse.io', 'lever.co', 'myworkdayjobs.com', 'icims.com', 'jobvite.com', 'workable.com', 'smartrecruiters.com', 'bamboohr.com', 'applytojob.com', 'applicantpro.com', 'jazz.co', 'jazzhr.com', 'paylocity.com', 'ultipro.com', 'ukg.net', 'adp.com']

function csv(text: string) { const rows:string[][]=[]; let r:string[]=[],v='',q=false; for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){r.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;r.push(v);if(r.some(Boolean))rows.push(r);r=[];v=''}else v+=c}if(v||r.length)rows.push([...r,v]);const[h=[],...data]=rows;return data.map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]??'']))) as Row[] }
function esc(v:unknown){const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
async function save(rows:Row[]){const h=rows.length?Object.keys(rows[0]):[];await writeFile(OUTPUT,`${[h.join(','),...rows.map(r=>h.map(k=>esc(r[k])).join(','))].join('\n')}\n`)}
function host(u:string){try{return new URL(u).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function internal(u:string,d:string){const h=host(u);return h===d||h.endsWith(`.${d}`)}
function ats(u:string){const h=host(u);return ATS.some(x=>h===x||h.endsWith(`.${x}`))}
function career(u:string){try{return /(^|\/)(?:careers?|jobs?|employment|openings?|positions?)(?:[\/_-]|$)|(^|\/)(?:career|employment)[-_]?(?:opportunit(?:y|ies)|openings?|positions?|vacancies)(?:\/|$)/i.test(new URL(u).pathname)}catch{return false}}
function detail(u:string,d:string){try{const p=new URL(u).pathname.toLowerCase(),tail=p.split('/').filter(Boolean).at(-1)??'';return internal(u,d)&&career(u)&&!/^(job|jobs|career|careers|employment|position|positions|opening|openings|opportunities|vacancies|hiring)$/.test(tail)&&!/(application|apply|referral|student|tag|category|blog)/.test(p)}catch{return false}}
function links(html:string,base:string){const out:string[]=[];for(const m of html.matchAll(/<a\b[^>]*?href=["']([^"'#]+)["']/gi)){try{out.push(new URL(m[1],base).href)}catch{}}return out}
function text(html:string){return html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function words(s:string){return s.match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu)?.length??0}
function complete(html:string,row:Row){const t=text(html);const location=/\b(location|remote|hybrid|on[- ]site|based in)\b/i.test(t)||t.includes(row.city)||new RegExp(`\\b${row.state}\\b`).test(t);const type=/\b(full[- ]?time|part[- ]?time|contract(?:or)?|temporary|seasonal|intern(?:ship)?|1099|per[- ]?diem|prn)\b/i.test(t);const structure=/\b(responsibilit(?:y|ies)|duties|requirements|qualifications|job description|what you(?:'|’)ll do)\b/i.test(t);return {ok:words(t)>=300&&location&&type&&structure,wordCount:words(t),location,type}}
async function get(url:string){const response=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; SolarRoles job research)'} ,signal:AbortSignal.timeout(20000)});return {url:response.url,ok:response.ok,html:await response.text()}}
async function serper(row:Row,key:string){const response=await fetch('https://google.serper.dev/search',{method:'POST',headers:{'X-API-KEY':key,'Content-Type':'application/json'},body:JSON.stringify({q:`\"${row.businessName}\" \"${row.city}\" California careers jobs`,gl:'us',hl:'en',num:20})});const body=await response.text();if(!response.ok)throw new Error(`Serper ${response.status}: ${body.slice(0,300)}`);return (JSON.parse(body) as {organic?:Result[]}).organic??[]}

async function main(){const source=csv(await readFile(INPUT,'utf8')).filter(r=>r.discoveryStatus==='candidate_found');let out:Row[]=[];try{out=csv(await readFile(OUTPUT,'utf8'))}catch{}const done=new Set(out.map(r=>r.licenseNumber));const pending=source.filter(r=>!done.has(r.licenseNumber));console.log(`Candidates: ${source.length}; saved: ${out.length}; remaining: ${pending.length}`)
for(const row of pending){let status='rejected_no_careers_page',reason='',careerUrl='',jobUrls:string[]=[],valid=0,atsFound=false,schema=false,maxWords=0;try{const domain=row.candidateDomain;const home=await get(`https://${domain}`);let urls=links(home.html,home.url).filter(u=>internal(u,domain));careerUrl=urls.find(career)??'';if(!careerUrl){for(const suffix of ['/careers','/jobs','/employment','/career','/about/careers','/about/career-opportunities']){const probe=await get(`https://${domain}${suffix}`);if(probe.ok){careerUrl=probe.url;urls=[...urls,...links(probe.html,probe.url)];break}}}if(!careerUrl)reason='No internal careers/jobs page found.';else{const page=await get(careerUrl);atsFound=atsFound||ats(page.url)||ATS.some(x=>page.html.includes(x));schema=/["']@type["']\s*:\s*["']JobPosting["']/i.test(page.html);jobUrls=[...new Set([...urls,...links(page.html,page.url)])].filter(u=>detail(u,domain));if(atsFound){status='rejected_ats_detected';reason='ATS detected on the career page.'}else if(schema){status='rejected_jobposting_detected';reason='JobPosting schema detected on the career page.'}else if(jobUrls.length<MIN_JOBS){status='rejected_insufficient_job_urls';reason=`Only ${jobUrls.length}/${MIN_JOBS} static job URLs found.`}else{for(const url of jobUrls.slice(0,8)){const job=await get(url);atsFound||=ats(job.url)||ATS.some(x=>job.html.includes(x));schema||=/["']@type["']\s*:\s*["']JobPosting["']/i.test(job.html);const check=complete(job.html,row);maxWords=Math.max(maxWords,check.wordCount);if(check.ok)valid++;if(valid>=MIN_JOBS||atsFound||schema)break}if(atsFound){status='rejected_ats_detected';reason='ATS detected on a job page.'}else if(schema){status='rejected_jobposting_detected';reason='JobPosting schema detected on a job page.'}else if(valid<MIN_JOBS){status='rejected_incomplete_job_pages';reason=`Only ${valid}/${MIN_JOBS} pages met description, location and employment-type criteria.`}else{status='validated_custom_scrape_candidate';reason='Static employer job pages meet all criteria.'}}}}catch(e){status='audit_error';reason=e instanceof Error?e.message:String(e)}out.push({licenseNumber:row.licenseNumber,businessName:row.businessName,city:row.city,state:row.state,candidateDomain:row.candidateDomain,careerUrl,jobUrls:jobUrls.slice(0,20).join('|'),jobUrlCount:String(jobUrls.length),validJobPages:String(valid),maxDescriptionWords:String(maxWords),atsDetected:String(atsFound),jobPostingDetected:String(schema),auditStatus:status,auditReason:reason});await save(out);console.log(`[${out.length}/${source.length}] ${row.businessName} — ${status}`)}console.log(`Valid: ${out.filter(r=>r.auditStatus==='validated_custom_scrape_candidate').length}/${out.length}`)}
main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1})
