import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

type Row = Record<string, string>;
type Result = { title?: string; url?: string; content?: string; score?: number };
const INPUT = path.join(process.cwd(), 'data', 'texas-solar-electrical-contractors', 'texas-solar-electrical-contractors.csv');
const OUTPUT = path.join(process.cwd(), 'data', 'texas-solar-electrical-contractors', 'texas-solar-domain-discovery-searxng-v2.csv');
const REQUEST_DELAY_MS = 3_000;
const EXCLUDED = new Set(['angi.com','austinenergy.com','bbb.org','bebee.com','bidroom.io','bizapedia.com','buildzoom.com','cityof.com','dnb.com','energysage.com','enfsolar.com','facebook.com','google.com','homeadvisor.com','indeed.com','instagram.com','linkedin.com','manta.com','pacermonitor.com','prolistlocal.com','scribd.com','solarreviews.com','thumbtack.com','yelp.com','youtube.com','yellowpages.com','zoominfo.com']);

function csv(source: string): Row[] { const records:string[][]=[];let row:string[]=[],value='',quoted=false;for(let i=0;i<source.length;i++){const char=source[i],next=source[i+1];if(char==='"'){if(quoted&&next==='"'){value+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(value);value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')i++;row.push(value);if(row.some(Boolean))records.push(row);row=[];value=''}else value+=char}if(value||row.length)records.push([...row,value]);const[headers=[],...rows]=records;return rows.map(record=>Object.fromEntries(headers.map((header,index)=>[header,record[index]??'']))); }
function esc(value: unknown){const text=String(value??'');return /[",\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
async function save(rows:Row[]){const headers=rows.length?Object.keys(rows[0]):[];await writeFile(OUTPUT,`${[headers.join(','),...rows.map(row=>headers.map(header=>esc(row[header])).join(','))].join('\n')}\n`,'utf8');}
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'').toLowerCase()}catch{return '';}}
function excluded(domain:string){return [...EXCLUDED].some(entry=>domain===entry||domain.endsWith(`.${entry}`));}
function tokens(name:string){return name.toLowerCase().match(/[a-z0-9]{2,}/g)?.filter(word=>!['solar','electric','electrical','energy','inc','llc','corp','company','texas','and','the'].includes(word)).slice(0,4)??[];}
function select(row:Row,results:Result[]){const words=tokens(row.businessName);return results.map(result=>{const domain=host(result.url??''),text=`${result.title??''} ${result.content??''} ${domain}`.toLowerCase(),domainMatches=words.filter(word=>domain.includes(word)).length,textMatches=words.filter(word=>text.includes(word)).length;return{result,domain,domainMatches,score:domainMatches*3+textMatches+(result.score??0)};}).filter(candidate=>candidate.domain&&!excluded(candidate.domain)&&(candidate.domainMatches>0||candidate.score>=6)).sort((a,b)=>b.score-a.score)[0];}
async function search(row:Row,baseUrl:string){const query=`"${row.businessName}" "${row.cityStateZip}" Texas solar contractor official website`;const response=await fetch(`${baseUrl.replace(/\/$/,'')}/search?q=${encodeURIComponent(query)}&format=json`,{signal:AbortSignal.timeout(30_000)});if(!response.ok)throw new Error(`SearXNG ${response.status}`);return{query,results:((await response.json())as{results?:Result[]}).results??[]};}
async function main(){const baseUrl=process.env.SEARXNG_BASE_URL;if(!baseUrl)throw new Error('Missing SEARXNG_BASE_URL in .env');const args=process.argv.slice(2),limit=Number(args[args.indexOf('--limit')+1])||Number.MAX_SAFE_INTEGER,concurrency=Number(args[args.indexOf('--concurrency')+1])||1,input=(csv(await readFile(INPUT,'utf8'))).slice(0,limit);let output:Row[]=[];try{output=csv(await readFile(OUTPUT,'utf8'))}catch{}const done=new Set(output.map(row=>row.licenseNumber)),pending=input.filter(row=>!done.has(row.licenseNumber));await mkdir(path.dirname(OUTPUT),{recursive:true});console.log(`Selected: ${input.length}; already saved: ${output.length}; remaining: ${pending.length}; delay: ${REQUEST_DELAY_MS}ms`);for(let start=0;start<pending.length;start+=concurrency){const batch=await Promise.all(pending.slice(start,start+concurrency).map(async row=>{try{const found=await search(row,baseUrl),candidate=select(row,found.results);return{...row,searxngQuery:found.query,candidateDomain:candidate?.domain??'',candidateUrl:candidate?.result.url??'',candidateTitle:candidate?.result.title??'',candidateSnippet:candidate?.result.content??'',discoveryStatus:candidate?'candidate_found':'no_official_domain_candidate',discoveryError:''};}catch(error){return{...row,searxngQuery:'',candidateDomain:'',candidateUrl:'',candidateTitle:'',candidateSnippet:'',discoveryStatus:'search_error',discoveryError:error instanceof Error?error.message:String(error)};}}));output.push(...batch);await save(output);for(const result of batch)console.log(`[${output.indexOf(result)+1}/${input.length}] ${result.businessName} — ${result.discoveryStatus}${result.candidateDomain?` (${result.candidateDomain})`:''}`);if(start+concurrency<pending.length)await new Promise(resolve=>setTimeout(resolve,REQUEST_DELAY_MS));}console.log(`Finished. Candidate domains: ${output.filter(row=>row.discoveryStatus==='candidate_found').length}/${output.length}`);}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1;});
