import path from 'node:path'
import type { HistoricalEmployer } from './commonCrawl'

export interface UrlIndexTarget {
  employerId: string
  employerName: string
  atsProvider: string
  pattern: string
  host: string
  pathPrefix: string
}

export interface UrlIndexSqlOptions {
  crawlIds: string[]
  parquetUrls: string[]
  targets: UrlIndexTarget[]
  outputDir: string
}

function sqlString(value: string) {
  return `'${value.replaceAll("'", "''")}'`
}

function sqlPath(value: string) {
  return sqlString(path.resolve(value).replaceAll('\\', '/'))
}

function chunks<T>(values: T[], size: number) {
  return Array.from({ length: Math.ceil(values.length / size) }, (_, index) => values.slice(index * size, (index + 1) * size))
}

export function surtHostPrefix(host: string) {
  return `${host.toLowerCase().split('.').reverse().join(',')})`
}

export function targetFromPattern(employer: HistoricalEmployer, pattern: string): UrlIndexTarget {
  const normalized = pattern.trim().replace(/^https?:\/\//i, '')
  const slash = normalized.indexOf('/')
  const host = (slash < 0 ? normalized : normalized.slice(0, slash)).toLowerCase()
  const rawPath = slash < 0 ? '/' : `/${normalized.slice(slash + 1)}`

  if (!host || /[*?]/.test(host)) {
    throw new Error(`URL Index patterns require an exact host: ${pattern}`)
  }
  if (/[*?]/.test(rawPath.replace(/\*$/, ''))) {
    throw new Error(`Only a trailing path wildcard is supported: ${pattern}`)
  }

  const withoutWildcard = rawPath.replace(/\*$/, '')
  const pathPrefix = withoutWildcard === '' ? '/' : withoutWildcard.toLowerCase()
  return {
    employerId: employer.employerId,
    employerName: employer.employerName,
    atsProvider: employer.atsProvider,
    pattern,
    host,
    pathPrefix,
  }
}

export function targetsFromEmployers(employers: HistoricalEmployer[]) {
  return employers.flatMap((employer) => employer.patterns.map((pattern) => targetFromPattern(employer, pattern)))
}

export function buildUrlIndexSql({ crawlIds, parquetUrls, targets, outputDir }: UrlIndexSqlOptions) {
  if (!crawlIds.length) throw new Error('At least one crawl ID is required')
  if (!parquetUrls.length) throw new Error('At least one Parquet URL is required')
  if (!targets.length) throw new Error('At least one URL target is required')
  for (const crawlId of crawlIds) {
    if (!/^CC-MAIN-\d{4}-\d{2}$/.test(crawlId)) throw new Error(`Invalid crawl ID: ${crawlId}`)
  }

  const hosts = [...new Set(targets.map((target) => target.host))].map(sqlString).join(', ')
  const surtRanges = [...new Set(targets.map((target) => surtHostPrefix(target.host)))]
    .map((prefix) => `(url_surtkey >= ${sqlString(prefix)} AND url_surtkey < ${sqlString(`${prefix}~`)})`)
    .join('\n    OR ')
  const parquetInserts = chunks(parquetUrls, 10).map((urls) => `INSERT INTO index_source
SELECT
  crawl,
  url_surtkey,
  url,
  lower(url_host_name) AS url_host_name,
  coalesce(url_path, '/') AS url_path,
  fetch_time,
  fetch_status,
  content_digest,
  content_mime_type,
  content_mime_detected,
  content_charset,
  content_languages,
  warc_filename,
  warc_record_offset,
  warc_record_length
FROM read_parquet([
    ${urls.map(sqlString).join(',\n    ')}
], hive_partitioning = true, union_by_name = true)
WHERE fetch_status = 200
  AND (
    ${surtRanges}
  )
  AND lower(url_host_name) IN (${hosts})
  AND (
    lower(coalesce(content_mime_type, '')) LIKE '%html%'
    OR lower(coalesce(content_mime_detected, '')) LIKE '%html%'
  );`).join('\n\n')
  const targetValues = targets.map((target) => `(${[
    target.employerId,
    target.employerName,
    target.atsProvider,
    target.pattern,
    target.host,
    target.pathPrefix,
  ].map(sqlString).join(', ')})`).join(',\n    ')

  const indexJson = sqlPath(path.join(outputDir, 'index-records.jsonl'))
  const indexParquet = sqlPath(path.join(outputDir, 'index-records.parquet'))
  const queryJson = sqlPath(path.join(outputDir, 'index-queries.jsonl'))
  const tempDirectory = sqlPath(path.join(outputDir, 'duckdb-tmp'))

  return `-- Generated by scripts/query-common-crawl-url-index.ts
INSTALL httpfs;
LOAD httpfs;
SET preserve_insertion_order = false;
SET enable_progress_bar = false;
SET http_retries = 10;
SET http_retry_wait_ms = 2000;
SET enable_http_metadata_cache = true;
SET threads = 1;
SET memory_limit = '1GB';
SET temp_directory = ${tempDirectory};

CREATE OR REPLACE TEMP TABLE url_targets (
  employer_id VARCHAR,
  employer_name VARCHAR,
  ats_provider VARCHAR,
  pattern VARCHAR,
  host VARCHAR,
  path_prefix VARCHAR
);

INSERT INTO url_targets VALUES
    ${targetValues};

CREATE OR REPLACE TEMP TABLE index_source (
  crawl VARCHAR,
  url_surtkey VARCHAR,
  url VARCHAR,
  url_host_name VARCHAR,
  url_path VARCHAR,
  fetch_time TIMESTAMP,
  fetch_status INTEGER,
  content_digest VARCHAR,
  content_mime_type VARCHAR,
  content_mime_detected VARCHAR,
  content_charset VARCHAR,
  content_languages VARCHAR,
  warc_filename VARCHAR,
  warc_record_offset BIGINT,
  warc_record_length BIGINT
);

${parquetInserts}

CREATE OR REPLACE TEMP TABLE index_matches AS
WITH ranked AS (
  SELECT
    source.*,
    target.employer_id,
    target.employer_name,
    target.ats_provider,
    target.pattern,
    row_number() OVER (
      PARTITION BY source.crawl, target.employer_id, source.url, source.content_digest,
        source.warc_filename, source.warc_record_offset
      ORDER BY target.path_prefix DESC
    ) AS target_rank
  FROM index_source AS source
  JOIN url_targets AS target
    ON source.url_host_name = target.host
   AND (
     target.path_prefix = '/'
     OR starts_with(lower(source.url_path), target.path_prefix)
   )
)
SELECT * EXCLUDE (target_rank)
FROM ranked
WHERE target_rank = 1;

COPY (
  SELECT
    url_surtkey AS urlkey,
    strftime(fetch_time, '%Y%m%d%H%M%S') AS timestamp,
    url,
    content_mime_type AS mime,
    content_mime_detected AS "mime-detected",
    cast(fetch_status AS VARCHAR) AS status,
    content_digest AS digest,
    cast(warc_record_length AS VARCHAR) AS length,
    cast(warc_record_offset AS VARCHAR) AS "offset",
    warc_filename AS filename,
    content_languages AS languages,
    content_charset AS encoding,
    crawl AS "crawlId",
    cast(regexp_extract(crawl, 'CC-MAIN-([0-9]{4})-', 1) AS INTEGER) AS year,
    employer_id AS "employerId",
    employer_name AS "employerName",
    ats_provider AS "atsProvider",
    pattern
  FROM index_matches
  ORDER BY crawl, employer_id, timestamp, url
) TO ${indexJson} (FORMAT JSON, ARRAY false);

COPY (SELECT * FROM index_matches)
TO ${indexParquet} (FORMAT PARQUET, COMPRESSION ZSTD);

COPY (
  SELECT
    cast(regexp_extract(crawl_id, 'CC-MAIN-([0-9]{4})-', 1) AS INTEGER) AS year,
    crawl_id AS "crawlId",
    target.employer_id AS "employerId",
    target.pattern,
    count(matches.url) AS matches,
    CASE WHEN count(matches.url) > 0 THEN 'matched' ELSE 'searched_no_capture' END AS status
  FROM (
    SELECT unnest([${crawlIds.map(sqlString).join(', ')}]) AS crawl_id
  ) AS crawls
  CROSS JOIN url_targets AS target
  LEFT JOIN index_matches AS matches
    ON matches.crawl = crawls.crawl_id
   AND matches.employer_id = target.employer_id
   AND matches.pattern = target.pattern
  GROUP BY crawl_id, target.employer_id, target.pattern
  ORDER BY crawl_id, target.employer_id, target.pattern
) TO ${queryJson} (FORMAT JSON, ARRAY false);

SELECT
  crawl,
  count(*) AS index_matches,
  count(DISTINCT employer_id) AS employers_with_matches
FROM index_matches
GROUP BY crawl
ORDER BY crawl;
`
}
